- hosts: all
  gather_facts: False
  vars:
    commands:
    - cmdrunner
    - "set password={{ ansible_password }}"
    - "set os={{ ansible_network_os }}"
    - run
  tasks:
  - cli_command:
      command: "{{ commands|join('\n') }}"
    register: output
  - debug:
      var: output['stdout_lines']
