- hosts: all
  gather_facts: False
  vars:
    commands:
    - cmdrunner
    - !unsafe "set password={{ lookup('env', 'ansible_ssh_pass') }}"
    - "set os={{ ansible_network_os }}"
    - run
  tasks:
  - cli_command:
      command: "{{ commands|join('\n') }}"
    register: output
  - debug:
      var: output['stdout_lines']
