- hosts: all
  gather_facts: False
  vars:
    platform_show:
      eos: show running-config
      ios: show running-config
      nxos: show running-config
      vyos: show config

  tasks:
  - cli_command:
      command: "{{ platform_show[ansible_network_os] }}"
    register: output
  - debug:
      var: output['stdout_lines']
