- hosts: all
  gather_facts: False
  vars:
    platform_show:
      eos: show run
      ios: show run
      nxos: show run
      vyos: show config
    platform_comment:
      eos: '!'
      ios: '#'
      nxos: '#'
      vyos: '#'
  tasks:
  - cli_command:
      command: "{{ platform_comment[ansible_network_os] }}hostname={{ inventory_hostname }}"
  - cli_command:
      command: "{{ platform_show[ansible_network_os] }}"
    register: output
  - debug:
      var: output['stdout_lines']
